"""Official Python SDK for the AudD music recognition API."""
from audd._version import __version__
from audd.client import AsyncAudD, AudD, AudDEvent
from audd.errors import (
    AudDAPIError,
    AudDAuthenticationError,
    AudDBlockedError,
    AudDConnectionError,
    AudDCustomCatalogAccessError,
    AudDError,
    AudDInvalidAudioError,
    AudDInvalidRequestError,
    AudDNeedsUpdateError,
    AudDNotReleasedError,
    AudDQuotaError,
    AudDRateLimitError,
    AudDSerializationError,
    AudDServerError,
    AudDStreamLimitError,
    AudDSubscriptionError,
)
from audd.longpoll import AsyncLongpollConsumer, LongpollConsumer
from audd.models import (
    AppleMusicMetadata,
    DeezerMetadata,
    EnterpriseMatch,
    LyricsResult,
    MusicBrainzEntry,
    NapsterMetadata,
    RecognitionResult,
    SpotifyMetadata,
    Stream,
    StreamCallbackMatch,
    StreamCallbackNotification,
    StreamCallbackSong,
    StreamingProvider,
)

__all__ = [
    "AppleMusicMetadata",
    "AsyncAudD",
    "AsyncLongpollConsumer",
    "AudD",
    "AudDAPIError",
    "AudDAuthenticationError",
    "AudDBlockedError",
    "AudDConnectionError",
    "AudDCustomCatalogAccessError",
    "AudDError",
    "AudDEvent",
    "AudDInvalidAudioError",
    "AudDInvalidRequestError",
    "AudDNeedsUpdateError",
    "AudDNotReleasedError",
    "AudDQuotaError",
    "AudDRateLimitError",
    "AudDSerializationError",
    "AudDServerError",
    "AudDStreamLimitError",
    "AudDSubscriptionError",
    "DeezerMetadata",
    "EnterpriseMatch",
    "LongpollConsumer",
    "LyricsResult",
    "MusicBrainzEntry",
    "NapsterMetadata",
    "RecognitionResult",
    "SpotifyMetadata",
    "Stream",
    "StreamCallbackMatch",
    "StreamCallbackNotification",
    "StreamCallbackSong",
    "StreamingProvider",
    "__version__",
]
